### ISSUE TITLE
Additional text on Avatar upload about animated gifs

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#154]
While the max upload for avatars is 110x110, the max upload for animated gifs is 81x81. It'd be great if we could add text here (http://prntscr.com/5xz8by) explaining that the max upload for animated gifs is 81x81.

**Comment by adamlieb** [comment]
Originally referenced here https://www.dungeondefenders.com/2/topic/116839/see-comment?scrollTo=1097676#1097676

**Comment by olshiftyeye** [comment]
i was able to reproduce this with the images shown below. in the case of the larger image, it uploads fine and animates in the header and other places on the site, but doesn't animate on the forums. when i upload the smaller image, however, it animates everywhere without any issues.

##### didn't work
![](https://cloud.githubusercontent.com/assets/4674805/5979809/2bce3b06-a868-11e4-8711-339efddc7aa3.gif)

##### worked
![002](https://cloud.githubusercontent.com/assets/4674805/5979825/46a99d8a-a868-11e4-9059-80c98c6ada0c.gif)

we want users to be able to upload larger gifs and have them work everywhere. @sky-duxter could this possibly be a server config issue?

**Comment by olshiftyeye** [comment]
@sky-duxter, can you confirm whether this is related to https://github.com/DuxterInc/DungeonDefendersEternity/issues/722?

**Comment by AnthonyKinson** [comment]
This is more likely an issue with which image is being used in each location. To my knowledge, When an avatar is uploaded, we generate thumbnail versions of that image. When images are resized, animated gis lose their additional frames and are no longer animated. In cases where images are no bigger than the thumbnail, no resize processing is required, and the thumbnails retail their animation.

The reason this may be working on one place, and not another for large gifs, is because some areas of the site maybe using the resized thumbnail (lost animation) whilst other areas are using the full size image (always retains animation).

I believe the header is incorrectly using the full size image instead of the thumbnail. Using the full size version of the avatar is highly discouraged as it has the potential to increase page sizes quite a lot, which may impact performance of mobile devices significantly.

@sky-duxter will be able to confirm or deny everything I just said as I believe he wrote the image scaling stuff.

**Comment by olshiftyeye** [comment]
![](http://ss.imjp.me/20150203103738.png)

@mbizzle please update the "help" text here to read as follows:

"Files must be 5MB or smaller. For best results, 81 x 81 and square (larger dimensions can affect animated GIFs)."

please update the size of the preview avatar to 81 x 81 as well (currently it's 110 x 110).

**Comment by olshiftyeye** [comment]
good on staging. ready to deploy to production.
