### ISSUE TITLE
"No New Notifications" display changes

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#155]
http://prntscr.com/5xz8u2

This one is a personal pet peeve. When there are no new notifications, can we:

1)  Hide the black circle with numbers
2)  Change the exclamation mark circle from white to grey

**Comment by iamjohnp** [comment]
@iamisom i think we'll just get rid of the circle and number when notifications = 0. let me know if you're not ok with that.

**Comment by iamisom** [comment]
That works.

**Comment by iamjohnp** [comment]
@mbizzle can you please update the notifications counter in the header so that it does **not** show a counter when new notifications = zero?

was:
![](http://ss.imjp.me/20150128120218.png)

should be:
![](http://ss.imjp.me/20150128120853.png)

**Comment by iamisom** [comment]
I'd like to re-open this. The visual cue isn't strong enough between active and inactive. 

Facebook empty:  http://prntscr.com/609l00
Facebook filled:  http://prntscr.com/609lbo

Facebook's notifications always catch my eye, but I tend to glaze over our notifications. This may be an issue with the notification button. The white notification icon makes the notification button appear active at all times. But it might be an issue with the username box having a background color from the rest of the bar.

**Comment by olshiftyeye** [comment]
i definitely don't want to quibble about the design, but i'll say that facebook's notifications stand out more because you have three icons in a row:

![](http://ss.imjp.me/20150202150448.png)

as a result, when one is highlighted (along with the big red counter) there is some nice contrast that draws your eye:

![](http://ss.imjp.me/20150202150607.png)

the problem with the dd site(s) is that we only have one icon in the header. so no matter what color we use for the icon, there won't be the same level of contrast as on facebook, because there's no direct comparison to surrounding icons. so it's my opinion that the way to contrast active vs inactive is to add a UI element when you have notifications, which we've done with the notification counter. if you think that doesn't pop enough, i'd recommend we play with the color of that counter rather than the color of the icon itself.

if you disagree that's fine too. i just wanted to let you know the thinking behind my decision. just let me know how you want to proceed and we'll make it happen.

**Comment by iamisom** [comment]
I agree with what you've said. I think making the counter pop more might be a good approach here.

**Comment by olshiftyeye** [comment]
How does this look to you? Too clashy? or just the right amount of pop?

![](http://ss.imjp.me/20150202162905.png)

**Comment by iamisom** [comment]
It might be a little too clashy with the background color behind the notification icon.

![otiuz3f](https://cloud.githubusercontent.com/assets/9043673/6011519/a02566e2-ab0a-11e4-891b-065da97183d6.png)

Without the background color, the new pop stands out more. 

Here's my opinion:  The current background color behind the user profile/notification draws your eye to it. This works for new users, but eventually, you ignore it because it's constantly drawing your attention to it, even when there's nothing there that demands your attention. The reward of the loop is broken because the cue is constantly perceived as active. I'd love to hear your thoughts on this.

**Comment by iamisom** [comment]
Do we have any metrics on the # of users who click on this? I might be arguing about an issue that isn't an issue.

**Comment by olshiftyeye** [comment]
changing the background color of that area will take some effort and time. i think we'd get the most "bang for our buck" by changing the counter background to red. when you don't have new notifs, it might still draw your eye (as you stated), but having that red up there really draws your eye more. it's my recommendation we go with the red counter bg and keep the same blue bg as it is.

**Comment by iamisom** [comment]
I understand. Let's move forward with the red circle change for now. 

Also, we should probably keep the black number for the DD1 site since the profile bar color is red. Thoughts?

**Comment by olshiftyeye** [comment]
I agree. @mbizzle take it away!

**Comment by olshiftyeye** [comment]
ready to deploy!

**Comment by olshiftyeye** [comment]
@iamisom this was just deployed.

**Comment by olshiftyeye** [comment]
@mbizzle looks like we only did the request below on DD2. can you please update DDE/DD1 as well?

> can you please update the notifications counter in the header so that it does not show a counter when new notifications = zero?

![](http://ss.imjp.me/20150218132114.png)

**Comment by rsyvarth** [comment]
This issue has been inactive for awhile and it doesn't seem like there is any further action necessary so I am going to go ahead and close the issue. If you still believe that there are changes that need to be made for this issue then please reopen it and reply with any specifics that you feel still need to be addressed.
