### ISSUE TITLE
List out any design-code inconsistencies

### ISSUE THREAD

**Issue by olshiftyeye** [DuxterInc/trendy-community#202]

**Comment by mbizzle** [comment]
![screen shot 2015-05-22 at 12 41 37 pm](https://cloud.githubusercontent.com/assets/316843/7778624/01dff9b6-0082-11e5-96fc-4b93cfeb3347.png)

the side margins for the footer links and the copyright text would be difficult to get exactly right due to it being dependent on the text size

also the 29px padding in the psd doesn't account for the descender and the ascender in the text which contribute to the overall line-height. I set the margins to 29px, but the  spacing won't be true to the psd provided
