### ISSUE TITLE
Can't use special characters in the Caption Contest

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#204]
https://www.dungeondefenders.com/2/topic/120218/add-common-special-characters-to-your-dd2-font#boxreply

**Comment by adamlieb** [comment]
This is an issue with the Single Sleeve font, it is simply missing these characters. We can switch the cap contest to a basic font and fix this immediately if you want.

**Comment by iamisom** [comment]
I believe our plan was to change this to the typical Impact font with the black outline that most memes use. Can we do that now? What would that look like?

**Comment by rsyvarth** [comment]
Here is a preview. Let me know what you think. I can get this out to production today if you are happy with that change.
![](http://ss.syvarth.com/20150601151449.png)

**Comment by iamisom** [comment]
That looks great, imo. Approved.

**Comment by rsyvarth** [comment]
New font has been pushed to production. I also included (what I believe to be) a fix for the bug where no image will load when creating a caption. Let me know if you see the issue happen again, but I don't _think_ it should.

**Comment by iamisom** [comment]
http://prntscr.com/7caw5p

It looks like two different fonts are being used. Also, all captions should be caps locked by default like the old text.

I'll keep an eye out for reports of the caption loading bug. Thanks for fixing that!

**Comment by rsyvarth** [comment]
The issue here is that the second user doesn't have Impact installed on their computer and it is falling back on a font that doesn't look very similar to impact at all. Impact isn't a free font so we can't include it in the site without paying a licensing fee. For now I am going to update the fallback list to the following.
```
Impact, Haettenschweiler, 'Franklin Gothic Bold', Charcoal, 'Helvetica Inserat', 'Bitstream Vera Sans Bold', 'Arial Black', 'sans serif'
```
Browsers will move down this list until it finds a font that is present on the user's computer. This hopefully will get most if not all users on a font that at minimum looks close to Impact. 

I have added in forced uppercase. I will let you know when these changes are live.

**Comment by rsyvarth** [comment]
Live
